// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiLjZ7o5ds4cgornUr166xR6onoFgLnCM',
    appId: '1:19917079386:web:77dcf33c4f9f4556bae963',
    messagingSenderId: '19917079386',
    projectId: 'smoothgabo',
    authDomain: 'smoothgabo.firebaseapp.com',
    storageBucket: 'smoothgabo.appspot.com',
    measurementId: 'G-GNHYDW16B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI77fLMyM_B6wSzdDzEQ5xjaTbJxJvza8',
    appId: '1:19917079386:android:9a484d3c40adf90bbae963',
    messagingSenderId: '19917079386',
    projectId: 'smoothgabo',
    storageBucket: 'smoothgabo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwdld2kcyLkF19pNuJy30U6310SiB4Bk',
    appId: '1:19917079386:ios:351b2f03c484d4abbae963',
    messagingSenderId: '19917079386',
    projectId: 'smoothgabo',
    storageBucket: 'smoothgabo.appspot.com',
    iosClientId: '19917079386-c8jat0skib8e9vbk83jtsjshnf7dhl0t.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.gabo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmwdld2kcyLkF19pNuJy30U6310SiB4Bk',
    appId: '1:19917079386:ios:351b2f03c484d4abbae963',
    messagingSenderId: '19917079386',
    projectId: 'smoothgabo',
    storageBucket: 'smoothgabo.appspot.com',
    iosClientId: '19917079386-c8jat0skib8e9vbk83jtsjshnf7dhl0t.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.gabo',
  );
}
